matrix:
    include:
        - language: node_js
          before-install:
            - cd API
            - npm update
          install: 
            - npm install
          script:
            - yarn test
        - language: android
          dist: trusty
          android:
                components:
                    - build-tools-xx.x.x
                    - android-xx
          script:
		# android build test 